// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD.ProjectName.WebApp.Data;

#nullable disable

namespace SD.ProjectName.WebApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251217153200_AddPayoutPreferences")]
    partial class AddPayoutPreferences
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
                {
        #pragma warning disable 612, 618
                    modelBuilder.HasAnnotation("ProductVersion", "9.0.11");
        
                    modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                        {
                            b.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");
        
                            b.Property<string>("FriendlyName")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("Xml")
                                .HasColumnType("TEXT");
        
                            b.HasKey("Id");
        
                            b.ToTable("DataProtectionKeys");
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                        {
                            b.Property<string>("Id")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("ConcurrencyStamp")
                                .IsConcurrencyToken()
                                .HasColumnType("TEXT");
        
                            b.Property<string>("Name")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("NormalizedName")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
        
                            b.HasKey("Id");
        
                            b.HasIndex("NormalizedName")
                                .IsUnique()
                                .HasDatabaseName("RoleNameIndex");
        
                            b.ToTable("AspNetRoles", (string)null);
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                        {
                            b.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");
        
                            b.Property<string>("ClaimType")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("ClaimValue")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("RoleId")
                                .IsRequired()
                                .HasColumnType("TEXT");
        
                            b.HasKey("Id");
        
                            b.HasIndex("RoleId");
        
                            b.ToTable("AspNetRoleClaims", (string)null);
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                        {
                            b.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");
        
                            b.Property<string>("ClaimType")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("ClaimValue")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("TEXT");
        
                            b.HasKey("Id");
        
                            b.HasIndex("UserId");
        
                            b.ToTable("AspNetUserClaims", (string)null);
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                        {
                            b.Property<string>("LoginProvider")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("ProviderKey")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("ProviderDisplayName")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("UserId")
                                .IsRequired()
                                .HasColumnType("TEXT");
        
                            b.HasKey("LoginProvider", "ProviderKey");
        
                            b.HasIndex("UserId");
        
                            b.ToTable("AspNetUserLogins", (string)null);
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                        {
                            b.Property<string>("UserId")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("RoleId")
                                .HasColumnType("TEXT");
        
                            b.HasKey("UserId", "RoleId");
        
                            b.HasIndex("RoleId");
        
                            b.ToTable("AspNetUserRoles", (string)null);
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                        {
                            b.Property<string>("UserId")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("LoginProvider")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("Name")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("Value")
                                .HasColumnType("TEXT");
        
                            b.HasKey("UserId", "LoginProvider", "Name");
        
                            b.ToTable("AspNetUserTokens", (string)null);
                        });
        
                    modelBuilder.Entity("SD.ProjectName.WebApp.Data.ApplicationUser", b =>
                        {
                            b.Property<string>("Id")
                                .HasColumnType("TEXT");
        
                            b.Property<int>("AccessFailedCount")
                                .HasColumnType("INTEGER");
        
                            b.Property<string>("AccountStatus")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("AccountType")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("CompanyName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("ConcurrencyStamp")
                                .IsConcurrencyToken()
                                .HasColumnType("TEXT");
        
                            b.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
        
                            b.Property<bool>("EmailConfirmed")
                                .HasColumnType("INTEGER");
        
                            b.Property<DateTimeOffset?>("EmailVerificationSentAt")
                                .HasColumnType("TEXT");
        
                            b.Property<DateTimeOffset?>("EmailVerifiedAt")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");
        
                            b.Property<DateTimeOffset?>("KycApprovedAt")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("KycStatus")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("NotStarted");
        
                            b.Property<DateTimeOffset?>("KycSubmittedAt")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");
        
                            b.Property<bool>("LockoutEnabled")
                                .HasColumnType("INTEGER");
        
                            b.Property<DateTimeOffset?>("LockoutEnd")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("NormalizedEmail")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("NormalizedUserName")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
        
                            b.Property<bool>("OnboardingCompleted")
                                .HasColumnType("INTEGER");
        
                            b.Property<int>("OnboardingStep")
                                .HasColumnType("INTEGER");
        
                            b.Property<string>("PasswordHash")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("PayoutAccountNumber")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("PayoutBankName")
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("PayoutDefaultMethod")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("BankTransfer");
        
                            b.Property<string>("PayoutBeneficiaryName")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("PhoneNumber")
                                .HasColumnType("TEXT");
        
                            b.Property<bool>("PhoneNumberConfirmed")
                                .HasColumnType("INTEGER");
        
                            b.Property<bool>("RequiresKyc")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER")
                                .HasDefaultValue(false);
        
                            b.Property<string>("SecurityStamp")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("SellerType")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("Individual");
        
                            b.Property<string>("StoreContactEmail")
                                .HasMaxLength(320)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("StoreContactPhone")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("StoreDescription")
                                .HasMaxLength(1000)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("StoreLogoPath")
                                .HasMaxLength(260)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("StoreName")
                                .HasMaxLength(120)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("StoreWebsiteUrl")
                                .HasMaxLength(2048)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("TaxId")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");
        
                            b.Property<DateTimeOffset>("TermsAcceptedAt")
                                .HasColumnType("TEXT");
        
                            b.Property<DateTimeOffset?>("TwoFactorConfiguredAt")
                                .HasColumnType("TEXT");
        
                            b.Property<bool>("TwoFactorEnabled")
                                .HasColumnType("INTEGER");
        
                            b.Property<DateTimeOffset?>("TwoFactorLastUsedAt")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("TwoFactorMethod")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasDefaultValue("None");
        
                            b.Property<DateTimeOffset?>("TwoFactorRecoveryCodesGeneratedAt")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("UserName")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("VerificationAddress")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("VerificationContactPerson")
                                .HasMaxLength(150)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("VerificationPersonalIdNumber")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("VerificationRegistrationNumber")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");
        
                            b.HasKey("Id");
        
                            b.HasIndex("NormalizedEmail")
                                .HasDatabaseName("EmailIndex");
        
                            b.HasIndex("NormalizedUserName")
                                .IsUnique()
                                .HasDatabaseName("UserNameIndex");
        
                            b.HasIndex("StoreName")
                                .IsUnique()
                                .HasFilter("StoreName IS NOT NULL");
        
                            b.ToTable("AspNetUsers", (string)null);
                        });
        
                    modelBuilder.Entity("SD.ProjectName.WebApp.Data.LoginAuditEvent", b =>
                        {
                            b.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");
        
                            b.Property<string>("EventType")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");
        
                            b.Property<DateTimeOffset?>("ExpiresAt")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("IpAddress")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");
        
                            b.Property<bool>("IsUnusual")
                                .HasColumnType("INTEGER");
        
                            b.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("TEXT");
        
                            b.Property<string>("Reason")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
        
                            b.Property<bool>("Succeeded")
                                .HasColumnType("INTEGER");
        
                            b.Property<string>("UserAgent")
                                .HasMaxLength(256)
                                .HasColumnType("TEXT");
        
                            b.Property<string>("UserId")
                                .IsRequired()
                                .HasMaxLength(450)
                                .HasColumnType("TEXT");
        
                            b.HasKey("Id");
        
                            b.HasIndex("ExpiresAt");
        
                            b.HasIndex("OccurredAt");
        
                            b.HasIndex("UserId");
        
                            b.ToTable("LoginAuditEvents");
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                        {
                            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                        {
                            b.HasOne("SD.ProjectName.WebApp.Data.ApplicationUser", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                        {
                            b.HasOne("SD.ProjectName.WebApp.Data.ApplicationUser", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                        {
                            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
        
                            b.HasOne("SD.ProjectName.WebApp.Data.ApplicationUser", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
        
                    modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                        {
                            b.HasOne("SD.ProjectName.WebApp.Data.ApplicationUser", null)
                                .WithMany()
                                .HasForeignKey("UserId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();
                        });
        #pragma warning restore 612, 618
                }
    }
}
