using System.Globalization;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SD.ProjectName.Modules.Cart.Domain;

namespace SD.ProjectName.WebApp.Services;

public interface ICommissionInvoicePdfGenerator
{
    byte[] Generate(CommissionInvoice invoice);
}

public class CommissionInvoicePdfGenerator : ICommissionInvoicePdfGenerator
{
    public byte[] Generate(CommissionInvoice invoice)
    {
        QuestPDF.Settings.License = LicenseType.Community;
        var culture = CultureInfo.GetCultureInfo("pl-PL");
        var invoiceLabel = invoice.IsCreditNote ? "Credit note" : "Commission invoice";

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(30);
                page.DefaultTextStyle(TextStyle.Default.FontSize(11));
                page.Header().Row(row =>
                {
                    row.RelativeItem().Column(stack =>
                    {
                        stack.Item().Text(invoiceLabel).SemiBold().FontSize(20);
                        stack.Item().Text($"Invoice number: {invoice.Number}");
                        stack.Item().Text($"Issued at: {invoice.IssuedAt:yyyy-MM-dd}");
                        stack.Item().Text($"Period: {invoice.PeriodStart:yyyy-MM-dd} – {invoice.PeriodEnd:yyyy-MM-dd}");
                    });

                    row.ConstantItem(160).Column(stack =>
                    {
                        stack.Item().Text("Seller").SemiBold();
                        stack.Item().Text(invoice.SellerName);
                        stack.Item().Text($"Seller ID: {invoice.SellerId}");
                    });
                });

                page.Content().PaddingTop(15).Column(col =>
                {
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(5);
                            columns.RelativeColumn(2);
                            columns.RelativeColumn(2);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(CellStyle).Text("Description").SemiBold();
                            header.Cell().Element(CellStyle).Text("Type").SemiBold();
                            header.Cell().Element(CellStyle).Text("Amount").SemiBold();
                        });

                        foreach (var line in invoice.Lines.OrderBy(l => l.Id))
                        {
                            table.Cell().Element(CellStyle).Text(line.Description);
                            table.Cell().Element(CellStyle).Text(line.IsCorrection ? "Correction" : "Commission");
                            table.Cell().Element(CellStyle).AlignRight().Text(line.Amount.ToString("C", culture));
                        }
                    });

                    col.Item().PaddingTop(10).Row(row =>
                    {
                        row.RelativeItem();
                        row.ConstantItem(220).Column(stack =>
                        {
                            stack.Spacing(2);
                            stack.Item().Row(r =>
                            {
                                r.RelativeItem().Text("Subtotal");
                                r.ConstantItem(100).AlignRight().Text(invoice.Subtotal.ToString("C", culture));
                            });
                            stack.Item().Row(r =>
                            {
                                r.RelativeItem().Text($"Tax ({invoice.TaxRate:P0})");
                                r.ConstantItem(100).AlignRight().Text(invoice.TaxAmount.ToString("C", culture));
                            });
                            stack.Item().LineHorizontal(1);
                            stack.Item().Row(r =>
                            {
                                r.RelativeItem().Text(invoice.IsCreditNote ? "Total credit" : "Total due").SemiBold();
                                r.ConstantItem(100).AlignRight().Text(invoice.TotalAmount.ToString("C", culture)).SemiBold();
                            });
                        });
                    });

                    col.Item().PaddingTop(10).Text("This document summarizes monthly commission fees. Corrections are shown as credit amounts when applicable.")
                        .FontSize(9)
                        .FontColor(Colors.Grey.Medium);
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Mercato");
                });
            });
        }).GeneratePdf();
    }

    private static IContainer CellStyle(IContainer container)
    {
        return container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(4);
    }
}
